ruby: https://www.railstutorial.org/
author: "http://www.michaelhartl.com/"
news: "http://news.railstutorial.org/"
avatar: http://gravatar.com/emails
max_name: 50
max_email: 255
min_password: 6
email_regex: !ruby/regexp /\A[a-z0-9\+\-_\.]+@[a-z\d\-.]+\.[a-z]+\z/i
size_avatar: 80
accountPerPage: 10
hour_expired: 2
content_post: 140
image_size: 5
bit_image: 1024

