ruby: https://www.railstutorial.org/
author: "http://www.michaelhartl.com/"
news: "http://news.railstutorial.org/"
max_name: 50
max_email: 255
min_password: 6
email_regex: !ruby/regexp /\A[a-z0-9\+\-_\.]+@[a-z\d\-.]+\.[a-z]+\z/i
